# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5330e85a27ad89fcaa22785ab0bc6a25ee90f9f3f9358fb5e16aedf4a075a3044ba226e9f546a9cde887f4b8d57ed79b929e0f5c186e90123d56345db779f84f

test:
  secret_key_base: 33c9ef83c736826cd86efb92398ec44aa0b3332b799befb7883a9461ffa0eea4e5f779afc487029ce81f0e267be9b62362ad00fb4b790a3a09404e708aeb7809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
